# Generated by Django 4.2.4 on 2023-11-18 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmbulanceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_time", models.DateTimeField(auto_now_add=True)),
                ("sent", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fin_code", models.CharField(max_length=7)),
                ("password", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("surname", models.CharField(max_length=50)),
                ("patrical_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(name="LoginModel",),
        migrations.AddField(
            model_name="ambulancerequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app1.usermodel"
            ),
        ),
    ]
