# Generated by Django 4.2.4 on 2023-11-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_usermodel_groups_usermodel_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="usermodel", name="groups",),
        migrations.RemoveField(model_name="usermodel", name="is_active",),
        migrations.RemoveField(model_name="usermodel", name="is_staff",),
        migrations.RemoveField(model_name="usermodel", name="is_superuser",),
        migrations.RemoveField(model_name="usermodel", name="last_login",),
        migrations.RemoveField(model_name="usermodel", name="user_permissions",),
    ]
