# Generated by Django 4.2.4 on 2023-11-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_remove_usermodel_groups_remove_usermodel_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="ambulancerequest", name="user",),
        migrations.AddField(
            model_name="ambulancerequest",
            name="fin_code",
            field=models.CharField(default="1234567", max_length=7),
        ),
        migrations.AddField(
            model_name="ambulancerequest",
            name="name",
            field=models.CharField(default="1234567", max_length=50),
        ),
        migrations.AddField(
            model_name="ambulancerequest",
            name="patrical_name",
            field=models.CharField(default="1234567", max_length=50),
        ),
        migrations.AddField(
            model_name="ambulancerequest",
            name="surname",
            field=models.CharField(default="1234567", max_length=50),
        ),
    ]
